name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build CBCHAIN
    runs-on: ubuntu-latest
    steps:

      # CHECKOUT
      - uses: actions/checkout@v3

      # PREPARE
      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      # BUILD
      - name: Build with Gradle
        run: ./gradlew clean build

      # PUBLISH
      - name: Build artifacts
        run: ./gradlew publish

      - name: Publish Artifact to GIT REPO
        uses: SpinyOwl/publish-artifact-to-git@1.0.1
        if: "!contains(github.event.head_commit.message, '[skip publish]')"
        with:
          repository: SpinyOwl/repo
          branch: releases
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: build/publish
          no_delete: true
